title: curatedQM9
logo: conngo.gif
description: 3054 molecules in the QM9 dataset were curated using CONNectivity preserving Geometry Optimization (ConnGO)
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
defaults:
  layout: single
